server:
  port: 8080
  servlet:
    session:
      timeout: 2H

spring:
  config:
    location:
  # mysql配置
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: gateway
    password: b853dff94d6742d5be3135f3987fc1d0
    url: jdbc:mysql://10.0.4.17:3307/wechatlog-test?cuseUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8

# 图书馆配置
library:
  isbnUrl: https://api.jike.xyz/situ/book/isbn/
  apiKey: 13491.5ce7c937cb631599fa40ae227ab62c11.642acb50785256f9f8a93097b62d591d